### PR TITLE
Additions and Deletions to the README, to make for better documentation

### PR DESCRIPTION
**Pull request by corlettim**
This PR is to update the README for better documentation. Paragraphs become condensed, which can be seen in the installation, testing, and running GatorGrader sections. As well as a rearrangement of information for a more sequential order. A section with comparisons to similar tools has been added as well.

### CODE REVIEW

**Comment by Michionlion** [comment]
Hi @corlettim, looks like there may have been some problems when you merged master into your branch -- there are some deletions in `README.md` (like that badges) that should be reverted. I would also ask that you check the issues in the Codacy review as well, to try and generate a positive PR.

**Comment by corlettim** [comment]
@Michionlion I checked my .gitignore file and it already has the `.DS_Store` in it. Is there something I am missing or does it need to be placed somewhere else within the .gitignore file?

**Comment by Michionlion** [comment]
> @Michionlion I checked my .gitignore file and it already has the `.DS_Store` in it. Is there something I am missing or does it need to be placed somewhere else within the .gitignore file?

You've still added a `.DS_Store` file -- check the "Files Changed" tab in Github to see all of the changes; the `.DS_Store` file can be seen there. You just need to remove it.

**Comment by corlettim** [comment]
> > @Michionlion I checked my .gitignore file and it already has the `.DS_Store` in it. Is there something I am missing or does it need to be placed somewhere else within the .gitignore file?
> 
> You've still added a `.DS_Store` file -- check the "Files Changed" tab in Github to see all of the changes; the `.DS_Store` file can be seen there. You just need to remove it.

Ok, I think I got it.

**Comment by gkapfham** [comment]
Hi @Michionlion and @corlettim, thanks for this effort! If I want to make tweaks to the writing, do you prefer that I do so in this PR door in a new one? Either way, I can start on this first thing in Friday. If I don't hear from you, I will keep adding to this open PR, okay?

**Comment by Michionlion** [comment]
> Hi @Michionlion and @corlettim, thanks for this effort! If I want to make tweaks to the writing, do you prefer that I do so in this PR door in a new one? Either way, I can start on this first thing in Friday. If I don't hear from you, I will keep adding to this open PR, okay?

I think this one should be merged before the appveyor support, so perhaps a new one.

**Comment by corlettim** [comment]
> > Hi @Michionlion and @corlettim, thanks for this effort! If I want to make tweaks to the writing, do you prefer that I do so in this PR door in a new one? Either way, I can start on this first thing in Friday. If I don't hear from you, I will keep adding to this open PR, okay?
> 
> I think this one should be merged before the appveyor support, so perhaps a new one.

I would be fine with either. But since @Michionlion thinks it would be best to put it in a new one, then we can do that!

**Pull request merged**
