### PR TITLE
Repository Must Handle Non-Git Directories

### LINKED ISSUE #137: Checks on Git Repository Crash when Run in Non-Repository
Although I have not yet tested this extensively, I have observed that GatorGrader checks for, say, the number of commits in a Git repository will lead to a tool crash when run in a directory that is not, in fact, a GitHub repository. This means that we should instead be first checking to ensure that GatorGrader is in a Git repository before the checks are actually run. I will confirm this issue and share a crash report at a later date.

### PR DESCRIPTION
**Pull request by gkapfham**
There is a bug in the `repository` module that will cause it to crash when the `get_commits` function is called with a path parameter that does not contain a Git repository. The purpose of this PR is to fix this bug and to add test cases for the new features and checks now provided.

Please note that this PR has already merged in all of the changes for the PR #166.

This PR is a bugfix that fixes #137.

### CODE REVIEW

**Comment by gkapfham** [comment]
Thanks for editing the PR description, @Michionlion. When I use `hub` to create the PRs, it is not following the PR template (although I have been told that it should). 

Side note: @Michionlion I think that it would be useful if we documented the meaning of these different changes that we can add (non-versioned ...). We might also want to clarify what we mean by major, minor, patch.

**Comment by Michionlion** [comment]
Also, @gkapfham, manually adding the `patch` label does not do anything -- it is only an indicator of the PR-Tag-Release's future intentions, and so the PR body must be updated (I've done so to match a patch change).

**Comment by gkapfham** [comment]
Thanks for approving these changes, @Michionlion. I think that I am now better understanding the way in which I write the PRs so that the tag release tool works correctly. I appreciate your clarifications.

**Comment by gkapfham** [comment]
@Michionlion and @schultzh and @corlettim I am going to go ahead and merge this PR as it fixes a bug in the way that GatorGrader handles the checking of the commit messages in a Git repository. Thanks!

**Pull request merged**
