### PR TITLE
Add metadata for PyPI publishing

### PR DESCRIPTION
**Pull request by Michionlion**
This PR contains metadata and configuration cleanup and additions to support publishing GatorGrader as a package on PyPI.

Among the many changes, here are the important highlights:

- Remove check "list" returns; instead, all checks should return a single boolean. This was a hold-over from
before GatorGrader was atomic in reference to checks.
- For internal checks, we use `pkgutil` to scan `gator.checks` and `importlib`
to import the requested check; this preserves functionality for when
GatorGrader will no longer have an easy to find "home" directory to pull python
source code from, as in an installed package.
- Clean up duplicated test fixtures.
- Separate CLI from API, expose API interface as `gator.grader(check_args)` (in source code as `gator/orchestrate.py::main_api(system_arguments: List[str])`)
- Remove last vestiges of "action queue" system, which relied heavily on reflection and was hard to read and maintain. The new paradigm, although more limited, is much clearer and easier to understand, which greatly increases maintainability
- Handle system and check argument errors better, printing/returning (with exceptions) more information.
- Remove "created parser" capability from checks. Now, the only way for a check to provide a parser is through the `get_parser` function, which should enable the same capabilities with a much simpler handling and implementation.
- Make ListChecks '--namecontains' searching option case insensitive
- Add documentation for PyPI release. Additionally, this makes the public interface available through
`import gatorgrader` well as `import gator`; `import gator` is recommended for now.

##### This PR has:

- [x] Commit messages that are correctly formatted
- [x] Tests for newly introduced code
- [x] Docstrings for newly introduced code

This PR is a non-versioned change.

#### Developers

@Michionlion

### CODE REVIEW

**Review by gkapfham — APPROVED** [review]
Hello @Michionlion, thanks for making these substantive changes to GatorGrader.

I can see the motivation behind all of these changes and I agree that they are needed.

Overall, I approve this PR. I suggest that you change the title of the PR to more clearly reflect the sweeping changes that this will make to GatorGrader on the whole.

Additional questions:

- Will GatorGradle be modified to reflect installation through `pip` and not through GitHub?
- Or, will it only be possible to use this version of GatorGrader through GatorGrade?

Are there other points that we should discuss before merging this PR? Thanks!

**Comment by Michionlion** [comment]
Hi @gkapfham, GatorGradle will not be modified to support the `poetry` version of GatorGrader; I'm in the process of publishing GatorGradle 1.0.0, which will be the last release and fix some long-standing issues as well as default the GatorGrader version to v1.1.0 (which has had its versions pinned as well). In the process I've needed to grab the `gatored.org` domain, since the Gradle Plugin Portal now requires domain control.

**Comment by gkapfham** [comment]
Hi @Michionlion, if GatorGradle is not modified to support Poetry, then will it no longer be possible to use GatorGradle if we merge PRs that remove all of the Pipenv support? (I seem to recall that we are moving Pipenv support; let me know if that is not in fact the case as I am working from memory right now).

Also, I have the gatorgrader.org domain --- would that help and then not require you to hold onto the domain you purchased forever?

**Comment by Michionlion** [comment]
It will no longer be possible to use GatorGradle with *newer* versions of GatorGrader; old versions of GatorGrader will still work just fine, which is why the change to GatorGradle was needed (to remove the automatic installation of `master`, which is now not compatible).

**Comment by Michionlion** [comment]
As for the `gatored.org` domain, that was needed because GatorGradle's plugin id is `org.gatored.GatorGradle`. I'd like to not change that ID, to try and keep some backward-compatibility and ease-of-upgrading. I don't mind holding on to it, but if you'd like to use it to point to `cs.allegheny.edu` or the GitHub org or something, I think that would be a better use.

**Pull request merged**
