### PR TITLE
Improve and Fix Diagnostics for Paragraph Word Counting

### LINKED ISSUE #138: Feedback for failing minimum word count inadequate
When `--words` is used in `gatorgrader.yml` to require a minimum number of words is met in the paragraphs detected, the current feedback only tells the user of the smallest word count found in all of the paragraphs it checked. It would be much more useful to the user if instead it told how many words it found in each of the paragraphs. This would allow the user to keep track of their progress if they jump around between the paragraphs they write and are trying to meet a minimum set in this way. It will also help locate where the minimum is not being met such as in the case provided below.

Sample output: 
```
-~-  FAILURES  -~-

✘  The reflection.md in writing has at least 100 word(s) in every paragraph
   ➔  Found 99 word(s) in a paragraph of the specified file
```

### PR DESCRIPTION
**Pull request by gkapfham**
This pull request improves the diagnostic messages that are displayed when a check concerning the number of paragraphs in a technical writing document fails. The discuss of the need for this pull request's fix is described in Issue #138.

### What is the current behavior?

Currently, GatorGrader only gives a diagnostic to indicate that the check failed.

### What is the new behavior if this PR is merged?

GatorGrader now gives information about some/all of the paragraphs that are not passing the check.

#### Other information

Note that the initial purpose of this PR was to add the suitable word-count diagnostics. Ultimately, it became possible to also write tests to cover all of the uncovered branches as part of the major refactoring that was required to add the requested diagnostics. As such, this PR handles two issues.

##### This PR has:

- [X] Commit messages that are correctly formatted
- [X] Tests for newly introduced code
- [X] Docstrings for newly introduced code

This PR is a small change that fixes #138 and #168.

#### Developers

@gkapfham

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @Michionlion, I have finished this PR that improves the diagnostics for word paragraph counting.

Although the idea behind this PR is simple, the implementation is complex and, in my view, breaks the simplicity of a lot of the implementation because of the fact that the system must pass up through the call chain a dictionary for the paragraph number and the word count in a paragraph.

Part of the complexity arises from the fact that sometimes the code must pass up an empty dictionary when the word count check is not being performed. I also decided to only highlight the first paragraph and to use natural language in the diagnostic message. This means that GatorGrader now uses the `num2words` package to convert numbers to the appropriate ordinal words.

I am still not able to get manual testing to work correctly. Using a header like this:

```
---
version: fix/add-word-count-diagnostics
name: cmpsc-203-spring-2019-practical7
break: true
indent: 4
---
```

does not seem to use the correct branch, unless there is something that I do not understand. Is this still a feature that will be implemented eventually once the current PR is merged in GatorGradle?

If I can get manual testing to work better, then I think that I will have a better idea for some automated tests that I could write to ensure that the diagnostic message is automatically generated in the correct fashion. Can you please let me know if the `version` tag should already work? Or, will it work soon?

**Comment by Michionlion** [comment]
> Hello @Michionlion, I have finished this PR that improves the diagnostics for word paragraph counting.
> 
> Although the idea behind this PR is simple, the implementation is complex and, in my view, breaks the simplicity of a lot of the implementation because of the fact that the system must pass up through the call chain a dictionary for the paragraph number and the word count in a paragraph.
> 
> Part of the complexity arises from the fact that sometimes the code must pass up an empty dictionary when the word count check is not being performed. I also decided to only highlight the first paragraph and to use natural language in the diagnostic message. This means that GatorGrader now uses the `num2words` package to convert numbers to the appropriate ordinal words.
> 
> I am still not able to get manual testing to work correctly. Using a header like this:
> 
> ```
> ---
> version: fix/add-word-count-diagnostics
> name: cmpsc-203-spring-2019-practical7
> break: true
> indent: 4
> ---
> ```
> 
> does not seem to use the correct branch, unless there is something that I do not understand. Is this still a feature that will be implemented eventually once the current PR is merged in GatorGradle?
> 
> If I can get manual testing to work better, then I think that I will have a better idea for some automated tests that I could write to ensure that the diagnostic message is automatically generated in the correct fashion. Can you please let me know if the `version` tag should already work? Or, will it work soon?

The `version` tag should work currently for some situations, and the open PR in GatorGradle will improve the number of those situations. There are still some things that need to be added for it to work in all situations. I will work on that at some point in the next few days!

**Comment by gkapfham** [comment]
Hi @Michionlion, thanks for your feedback, I really appreciate it!

In an effort to improve the testing for some of the features in this PR, I went ahead and added test cases to cover branches that were not already covered by the test suite, thus resolving an outstanding issue.

In fact, this helped me to see several cases in which the test cases were not testing certain circumstances.

I plan to integrate this form of  coverage into our report to the CodeCov service.

**Comment by gkapfham** [comment]
Note that there were some clones that were detected in the test suite. However, once I log into the Codacy dashboard, these go away because I have configured that service to not look for code duplication in the tests; I think that duplication in a test suite is acceptable. I anticipate that these Codacy issues will go away the next time I run a build on this PR.

**Comment by gkapfham** [comment]
Hi @Michionlion it does, in fact, seem that toggling the setting to ignore the test files in Codacy re-enables this setting. As you can see, we are now back to the PR having a good score from that service. Is there something that I do not correctly understand about our integration with Codacy? Why do we have to re-enable the setting that stops the inspection of the test files for code duplication?

**Comment by Michionlion** [comment]
> Hi @Michionlion it does, in fact, seem that toggling the setting to ignore the test files in Codacy re-enables this setting. As you can see, we are now back to the PR having a good score from that service. Is there something that I do not correctly understand about our integration with Codacy? Why do we have to re-enable the setting that stops the inspection of the test files for code duplication?
> 
> ACTUALLY, I don't get it! The green checkmark toggled to an a red xmark while I was typing this comment the last time. How can we write code to configure to Codacy to avoid checking the test files?
> 
> FINAL NOTE: When I log into the Codacy dashboard, I see that Codacy ranks this PR as an A.

Honestly, I am not sure how Codacy deals with this kind of thing. We could reduce the criterion for a bad PR...

**Comment by gkapfham** [comment]
Hi @Michionlion, I delete the patch label for this PR.

**Comment by gkapfham** [comment]
Hi @Michionlion, should we delete the integration with Codacy? Can you suggest another tool that provides similar features and is free for open-source projects? Maybe we should consider:

https://codeclimate.com/quality/pricing/

Note that this tool seems to be free for open-source. I notice that this company is mainly pushing their Velocity product. But, I have noticed that other projects are using this Quality tool as well. Let me know what you think! Thanks!

**Pull request merged**
