### PR TITLE
Migrate to Poetry

### PR DESCRIPTION
**Pull request by Michionlion**
GatorGrader has long been plagued with a non-user friendly installation interface, and this PR is the first step to rectifying this. By migrating dependency management to Poetry, we will gain more flexibility (and simplicity) in how we architect publishing GatorGrader as a Python package on PyPI, and enabling workflows like `pipx run gatorgrader <some check arguments>` without any extra work needed by the user.

This PR is a non-versioned change.

This work-in-progress PR has the core dependency management and GitHub Actions workflow converted to use Poetry. Before marking this as ready for review, I'd like to simplify and merge many of the configuration files to reduce cognitive load for new contributors, and simplify the root directory.

#### Developers

@Michionlion

### CODE REVIEW

**Comment by gkapfham** [comment]
Hello @Michionlion, thanks for working on this PR! I think that it is a very good idea to migrate away from Pipenv and to start using Poetry. If there is anything that I need to do in terms of testing or revising some of the configuration files, please let me know. I am glad to help with this PR if you can see a way for me to appropriately contribute. Thanks! :rocket:

**Comment by Michionlion** [comment]
@gkapfham I think this PR is pretty much ready to be merged; it replaces and fully duplicates the existing functionality, although nothing new (like publishing a package to PyPI) has been added. The only reason I've hesitated is that we'll need to update GatorGradle to either use poetry itself (which shouldn't be that difficult), or to require a published python package is installed. Either option will break existing assignments that don't have an explicit version of GatorGrader specified (which I really would like to avoid), so merging this will probably need to wait until the week between Module 1 and Module 2.

**Review by mariakimheinert — DISMISSED** [review]
Looks good to me!

**Review by mariakimheinert — APPROVED** [review]
LGTM.

**Pull request merged**
